### ISSUE TITLE
Software failed to install

### ISSUE THREAD

**Issue by husseymj** [Achronite/node-red-contrib-energenie-ener314rt#35]
I'm a noob to this so need some plain English hand holding on this.

I just installed the energenie-ener314rt module, brand new from energenie. In other words I plugged it into my raspberry pi which is running both hassio and node red through the hassio apt.

This is the LOG of my failed installation, any help would be appreciated

Thanks

Mike
-----------------------------------------------------------
2020-04-27T15:02:11.030Z Install : node-red-contrib-energenie-ener314rt 0.3.8

2020-04-27T15:02:12.171Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-energenie-ener314rt@0.3.8
2020-04-27T15:02:45.285Z [out] 
2020-04-27T15:02:45.285Z [out] > mdns@2.5.1 install /config/node-red/node_modules/mdns
2020-04-27T15:02:45.285Z [out] > node-gyp rebuild
2020-04-27T15:02:45.285Z [out] 
2020-04-27T15:02:49.767Z [err] gyp
2020-04-27T15:02:49.770Z [err]  
2020-04-27T15:02:49.771Z [err] ERR!
2020-04-27T15:02:49.772Z [err]  
2020-04-27T15:02:49.772Z [err] build error
2020-04-27T15:02:49.773Z [err]  
2020-04-27T15:02:49.777Z [err] gyp
2020-04-27T15:02:49.778Z [err]  ERR! stack
2020-04-27T15:02:49.778Z [err]  Error: not found: make
2020-04-27T15:02:49.778Z [err] gyp ERR! stack
2020-04-27T15:02:49.779Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-04-27T15:02:49.779Z [err] gyp ERR! stack
2020-04-27T15:02:49.779Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-04-27T15:02:49.779Z [err] gyp ERR! stack
2020-04-27T15:02:49.779Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-04-27T15:02:49.779Z [err] gyp ERR! stack
2020-04-27T15:02:49.780Z [err]      at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-04-27T15:02:49.780Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-04-27T15:02:49.780Z [err] gyp 
2020-04-27T15:02:49.780Z [err] ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-04-27T15:02:49.780Z [err] gyp ERR! 
2020-04-27T15:02:49.781Z [err] stack     at FSReqCallback.oncomplete (fs.js:158:21)
2020-04-27T15:02:49.782Z [err] gyp 
2020-04-27T15:02:49.782Z [err] ERR! System Linux 4.19.114-v7
2020-04-27T15:02:49.783Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-04-27T15:02:49.783Z [err] gyp ERR! cwd
2020-04-27T15:02:49.783Z [err]  /config/node-red/node_modules/mdns
2020-04-27T15:02:49.783Z [err] gyp
2020-04-27T15:02:49.784Z [err]  ERR! 
2020-04-27T15:02:49.784Z [err] node -v v12.15.0
2020-04-27T15:02:49.784Z [err] gyp ERR! node-gyp -v
2020-04-27T15:02:49.784Z [err]  v5.0.5
2020-04-27T15:02:49.784Z [err] gyp
2020-04-27T15:02:49.785Z [err]  ERR! not ok
2020-04-27T15:02:49.785Z [err]  
2020-04-27T15:02:49.864Z [out] 
2020-04-27T15:02:49.864Z [out] > energenie-ener314rt@0.3.4 install /config/node-red/node_modules/energenie-ener314rt
2020-04-27T15:02:49.864Z [out] > node-gyp rebuild
2020-04-27T15:02:49.864Z [out] 
2020-04-27T15:02:53.102Z [err] gyp
2020-04-27T15:02:53.104Z [err]  
2020-04-27T15:02:53.104Z [err] ERR! build error 
2020-04-27T15:02:53.108Z [err] gyp
2020-04-27T15:02:53.109Z [err]  ERR! stack
2020-04-27T15:02:53.109Z [err]  Error: not found: make
2020-04-27T15:02:53.109Z [err] gyp 
2020-04-27T15:02:53.110Z [err] ERR! stack
2020-04-27T15:02:53.110Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-04-27T15:02:53.110Z [err] gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-04-27T15:02:53.110Z [err] gyp ERR! 
2020-04-27T15:02:53.111Z [err] stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-04-27T15:02:53.111Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-04-27T15:02:53.111Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-04-27T15:02:53.111Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-04-27T15:02:53.112Z [err] gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
2020-04-27T15:02:53.115Z [err] gyp ERR!
2020-04-27T15:02:53.115Z [err]  System Linux 4.19.114-v7
2020-04-27T15:02:53.115Z [err] gyp
2020-04-27T15:02:53.115Z [err]  ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-04-27T15:02:53.115Z [err] gyp ERR!
2020-04-27T15:02:53.115Z [err]  cwd /config/node-red/node_modules/energenie-ener314rt
2020-04-27T15:02:53.116Z [err] gyp ERR!
2020-04-27T15:02:53.116Z [err]  node -v
2020-04-27T15:02:53.116Z [err]  v12.15.0
2020-04-27T15:02:53.116Z [err] gyp 
2020-04-27T15:02:53.116Z [err] ERR! node-gyp -v
2020-04-27T15:02:53.117Z [err]  v5.0.5
2020-04-27T15:02:53.117Z [err] gyp ERR! 
2020-04-27T15:02:53.117Z [err] not ok 
2020-04-27T15:02:55.907Z [err] npm
2020-04-27T15:02:55.908Z [err]  WARN 
2020-04-27T15:02:55.908Z [err] optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.5.1 (node_modules/mdns):
2020-04-27T15:02:55.908Z [err] npm WARN optional
2020-04-27T15:02:55.908Z [err]  SKIPPING OPTIONAL DEPENDENCY: mdns@2.5.1 install: `node-gyp rebuild`
2020-04-27T15:02:55.908Z [err] npm 
2020-04-27T15:02:55.909Z [err] WARN optional
2020-04-27T15:02:55.909Z [err]  SKIPPING OPTIONAL DEPENDENCY: Exit status 1
2020-04-27T15:02:55.910Z [err] 
2020-04-27T15:02:55.954Z [err] npm
2020-04-27T15:02:55.954Z [err]  ERR! code ELIFECYCLE
2020-04-27T15:02:55.955Z [err] npm ERR! errno
2020-04-27T15:02:55.955Z [err]  1
2020-04-27T15:02:55.956Z [err] npm
2020-04-27T15:02:55.956Z [err]  ERR! energenie-ener314rt@0.3.4 install: `node-gyp rebuild`
2020-04-27T15:02:55.956Z [err] npm ERR!
2020-04-27T15:02:55.961Z [err]  Exit status 1
2020-04-27T15:02:55.961Z [err] npm ERR! 
2020-04-27T15:02:55.961Z [err] npm ERR! Failed at the energenie-ener314rt@0.3.4 install script.
2020-04-27T15:02:55.961Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-04-27T15:02:56.008Z [err] 
2020-04-27T15:02:56.008Z [err] npm ERR! A complete log of this run can be found in:
2020-04-27T15:02:56.008Z [err] npm ERR!     /root/.npm/_logs/2020-04-27T15_02_55_975Z-debug.log
2020-04-27T15:02:56.037Z rc=1

-----------------------------------------------------------
2020-04-27T15:06:48.814Z Install : node-red-contrib-energenie-ener314rt 0.3.8

2020-04-27T15:06:49.779Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-energenie-ener314rt@0.3.8
2020-04-27T15:07:19.465Z [out] 
2020-04-27T15:07:19.465Z [out] > mdns@2.5.1 install /config/node-red/node_modules/mdns
2020-04-27T15:07:19.465Z [out] > node-gyp rebuild
2020-04-27T15:07:19.465Z [out] 
2020-04-27T15:07:23.947Z [err] gyp
2020-04-27T15:07:23.949Z [err]  
2020-04-27T15:07:23.949Z [err] ERR! build error 
2020-04-27T15:07:23.953Z [err] gyp
2020-04-27T15:07:23.953Z [err]  ERR!
2020-04-27T15:07:23.953Z [err]  stack
2020-04-27T15:07:23.954Z [err]  Error: not found: make
2020-04-27T15:07:23.954Z [err] gyp ERR!
2020-04-27T15:07:23.954Z [err]  stack
2020-04-27T15:07:23.954Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-04-27T15:07:23.954Z [err] gyp 
2020-04-27T15:07:23.954Z [err] ERR! stack
2020-04-27T15:07:23.954Z [err]      at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-04-27T15:07:23.954Z [err] gyp
2020-04-27T15:07:23.955Z [err]  ERR!
2020-04-27T15:07:23.955Z [err]  stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-04-27T15:07:23.955Z [err] gyp ERR!
2020-04-27T15:07:23.955Z [err]  stack
2020-04-27T15:07:23.955Z [err]      at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-04-27T15:07:23.955Z [err] gyp
2020-04-27T15:07:23.956Z [err]  ERR! stack
2020-04-27T15:07:23.956Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-04-27T15:07:23.956Z [err] gyp 
2020-04-27T15:07:23.956Z [err] ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-04-27T15:07:23.956Z [err] gyp 
2020-04-27T15:07:23.956Z [err] ERR! stack
2020-04-27T15:07:23.957Z [err]      at FSReqCallback.oncomplete (fs.js:158:21)
2020-04-27T15:07:23.958Z [err] gyp 
2020-04-27T15:07:23.958Z [err] ERR! System Linux 4.19.114-v7
2020-04-27T15:07:23.959Z [err] gyp ERR!
2020-04-27T15:07:23.959Z [err]  command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-04-27T15:07:23.959Z [err] gyp ERR!
2020-04-27T15:07:23.959Z [err]  cwd /config/node-red/node_modules/mdns
2020-04-27T15:07:23.960Z [err] gyp ERR!
2020-04-27T15:07:23.960Z [err]  node -v
2020-04-27T15:07:23.960Z [err]  v12.15.0
2020-04-27T15:07:23.960Z [err] gyp 
2020-04-27T15:07:23.963Z [err] ERR! node-gyp -v v5.0.5
2020-04-27T15:07:23.963Z [err] gyp ERR! not ok 
2020-04-27T15:07:24.022Z [out] 
2020-04-27T15:07:24.022Z [out] > energenie-ener314rt@0.3.4 install /config/node-red/node_modules/energenie-ener314rt
2020-04-27T15:07:24.022Z [out] > node-gyp rebuild
2020-04-27T15:07:24.022Z [out] 
2020-04-27T15:07:27.180Z [err] gyp
2020-04-27T15:07:27.181Z [err]  
2020-04-27T15:07:27.182Z [err] ERR! build error 
2020-04-27T15:07:27.186Z [err] gyp
2020-04-27T15:07:27.186Z [err]  ERR! 
2020-04-27T15:07:27.186Z [err] stack Error: not found: make
2020-04-27T15:07:27.186Z [err] gyp ERR!
2020-04-27T15:07:27.192Z [err]  stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-04-27T15:07:27.192Z [err] gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-04-27T15:07:27.192Z [err] gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-04-27T15:07:27.192Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-04-27T15:07:27.192Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-04-27T15:07:27.192Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-04-27T15:07:27.192Z [err] gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
2020-04-27T15:07:27.192Z [err] gyp ERR! System Linux 4.19.114-v7
2020-04-27T15:07:27.192Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-04-27T15:07:27.192Z [err] gyp ERR! cwd /config/node-red/node_modules/energenie-ener314rt
2020-04-27T15:07:27.192Z [err] gyp ERR! node -v
2020-04-27T15:07:27.193Z [err]  v12.15.0
2020-04-27T15:07:27.193Z [err] gyp ERR! node-gyp -v v5.0.5
2020-04-27T15:07:27.193Z [err] gyp
2020-04-27T15:07:27.203Z [err]  ERR! not ok 
2020-04-27T15:07:30.027Z [err] npm
2020-04-27T15:07:30.029Z [err]  
2020-04-27T15:07:30.029Z [err] WARN
2020-04-27T15:07:30.030Z [err]  
2020-04-27T15:07:30.030Z [err] optional
2020-04-27T15:07:30.031Z [err]  SKIPPING OPTIONAL DEPENDENCY: mdns@2.5.1 (node_modules/mdns):
2020-04-27T15:07:30.032Z [err] npm
2020-04-27T15:07:30.032Z [err]  
2020-04-27T15:07:30.033Z [err] WARN
2020-04-27T15:07:30.033Z [err]  
2020-04-27T15:07:30.034Z [err] optional
2020-04-27T15:07:30.035Z [err]  SKIPPING OPTIONAL DEPENDENCY: mdns@2.5.1 install: `node-gyp rebuild`
2020-04-27T15:07:30.036Z [err] npm
2020-04-27T15:07:30.037Z [err]  
2020-04-27T15:07:30.038Z [err] WARN
2020-04-27T15:07:30.039Z [err]  
2020-04-27T15:07:30.040Z [err] optional
2020-04-27T15:07:30.041Z [err]  SKIPPING OPTIONAL DEPENDENCY: Exit status 1
2020-04-27T15:07:30.044Z [err] 
2020-04-27T15:07:30.087Z [err] npm
2020-04-27T15:07:30.089Z [err]  
2020-04-27T15:07:30.090Z [err] ERR!
2020-04-27T15:07:30.091Z [err]  
2020-04-27T15:07:30.093Z [err] code
2020-04-27T15:07:30.094Z [err]  ELIFECYCLE
2020-04-27T15:07:30.096Z [err] npm
2020-04-27T15:07:30.097Z [err]  
2020-04-27T15:07:30.098Z [err] ERR!
2020-04-27T15:07:30.108Z [err]  errno 1
2020-04-27T15:07:30.108Z [err] npm ERR! energenie-ener314rt@0.3.4 install: `node-gyp rebuild`
2020-04-27T15:07:30.108Z [err] npm ERR! Exit status 1
2020-04-27T15:07:30.108Z [err] npm ERR! 
2020-04-27T15:07:30.108Z [err] npm ERR! Failed at the energenie-ener314rt@0.3.4 install script.
2020-04-27T15:07:30.108Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-04-27T15:07:30.154Z [err] 
2020-04-27T15:07:30.154Z [err] npm ERR! A complete log of this run can be found in:
2020-04-27T15:07:30.154Z [err] npm ERR!     /root/.npm/_logs/2020-04-27T15_07_30_121Z-debug.log
2020-04-27T15:07:30.177Z rc=1

**Comment by Achronite** [comment]
Hassio / Home assistant is not supported, even when it does install I can't access GPIO.  I reached out to the community [here ](https://community.home-assistant.io/t/accessing-gpio-spi-from-custom-node-red-node-node-red-contrib-energenie-ener314rt/170002) to help but no-one answered.  I suggest you try native node-red support instead.

**Comment by Achronite** [comment]
Duplicated by issue #28.
